spring:
  data:
    mongodb:
      host: ${qMONGO_IP}
      port: ${MONGO_PORT}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PW}
      database: ${MONGO_DB_BRIDGE}
server:
  port: ${BRIDGE_PORT}