spring:
  data:
    mongodb:
      host: @MONGO_IP@
      port: @MONGO_PORT@
      username: @MONGO_USERNAME@
      password: @MONGO_PW@
      database: @MONGO_DB_BRIDGE@
server:
  port: @BRIDGE_PORT@