spring:
  data:
    mongodb:
      host: ${MONGO_IP}
      port: ${MONGO_PORT}
      username: ${MONGO_BRIDGE_USERNAME}
      password: ${MONGO_BRIDGE_PW}
      database: data
server:
  port: ${BRIDGE_PORT}