
data:
  mongodb:
    host: ${MONGO_IP}
    port: ${MONGO_PORT}
    username: ${MONGO_BRIDGE_USERNAME}
    password: ${MONGO_BRIDGE_PW}
    database: data

shopData:
  mongodb:
    host: ${MONGO_IP}
    port: ${MONGO_PORT}
    username: ${MONGO_BRIDGE_USER}
    password: ${MONGO_BRIDGE_PASSW}
    database: shopData
server:
  port: ${BRIDGE_PORT}