data:
  mongodb:
    host: ${MONGO_IP}
    port: ${MONGO_PORT}
    username: ${MONGO_BRIDGE_USERNAME}
    password: ${MONGO_BRIDGE_PW}
    database: data

shopData:
  mongodb:
    host: ${MONGO_IP}
    port: ${MONGO_PORT}
    username: ${MONGO_BRIDGE_USER}
    password: ${MONGO_BRIDGE_PASSW}
    database: shopData

idealobridge:
  oAuth2ClientId: ${CLIENT_ID}
  oAuth2ClientSecret: ${CLIENT_SECRET}
  accessTokenURI: ${ACCESS_TOKEN_URI}
  apiUrl: ${API_URL}
  randomOfferRoute: "/sampleOffers"

server:
  port: ${BRIDGE_PORT}