spring:
  data:
    mongodb:
      host: ${qMONGO_IP}
      port: Integer.parseInt(${MONGO_PORT})
      username: ${MONGO_USERNAME}
      password: ${MONGO_PW}
      database: ${MONGO_DB_BRIDGE}
server:
  port: Integer.parseInt(${BRIDGE_PORT})